config/routes.rb
CompositionCompetition::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  authenticated :user do
    root :to => 'home#authenticated_index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do 
    resources :stories
  end
  resources :competitions do
    resources :submissions do
      member {post :vote}
    end
  end
end

app/models/competition.rb
# == Schema Information
#
# Table name: competitions
#
#  id          :integer          not null, primary key
#  deadline    :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  title       :string(255)
#  user_id     :integer
#  public      :boolean          default(TRUE)
#  status      :integer          default(0)
#  description :text
#  slug        :string(255)
#

class Competition < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  attr_accessible :deadline, :title, :user_id, :public, :description
  STATUS = { active: 0, expired: 1, inactive: 2, deleted: 3 }

  belongs_to :owner, :class_name => User.name, :foreign_key => 'user_id'
  has_many :submissions, :dependent => :destroy

  has_many :competitor_submissions, :class_name => Submission.name, :conditions => {role: 0}
  has_many :competitors, :through => :competitor_submissions, :source => :user
  has_many :stories, :through => :competitor_submissions

  has_many :judge_submissions, :class_name => Submission.name, :conditions => {role: 2}
  has_many :judges, :through => :judge_submissions, :source => :user

  scope :expired,         -> { where("DATE(deadline) < ?", Date.today) }
  scope :expiring_today,  -> { where("DATE(deadline) = ?", Date.today) }
  scope :unexpired,       -> { where("DATE(deadline) >= ?", Date.today) }

  validates :title, :presence => true
  validates :owner, :presence => true
  validates :deadline, :format => { :with => /\d{4}-\d{2}-\d{2}/, :message => "Deadline must be YYYY-MM-DD" }
  validates :deadline, :presence => true
  validate  :deadline_cannot_be_in_the_past
  validates :description, :presence => true

  after_save :create_sample_submission

  def expires_today
    self.deadline == Date.today
  end

  def expired
    self.deadline.past?
  end

  def status
    STATUS.key(read_attribute(:status))
  end

  def status=(s)
    write_attribute(:status, STATUS[s])
  end

  def to_s
    self.title.titleize
  end

  private
    def create_sample_submission
      self.owner.submissions.create!(competition_id: self.id, role: :owner, active: false)
      self.owner.submissions.create!(competition_id: self.id, role: :judge, active: false)
    end

    def deadline_cannot_be_in_the_past
      if !deadline.blank? and deadline < Date.today
        errors.add(:deadline, "The deadline can't be in the past.")
      end
    end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  (skip_before_filter :authenticate_user!, :only => [:show]) if lambda { 
    if params[:id]
      @competition = Competition.find(params[:id])
      @competition and @competition.public?
    else
      false
    end
  }

  add_breadcrumb "Competitions", :competitions_path

  def new
    @competition = Competition.new
    session[:return_to] ||= request.env['HTTP_X_XHR_REFERER'] || request.referer # TODO: change this when turbolinks is updated
  end

  def create
    @competition = current_user.competitions.build(params[:competition])
    @competition.owner = current_user
    if @competition.save
      flash[:success] = "Competition created"
      redirect_to @competition
    else
      render :new
    end
  end

  def edit
    add_breadcrumb @competition, competition_path(@competition)
    add_breadcrumb "Edit", edit_competition_path(@competition)
    session[:return_to] ||= request.env['HTTP_X_XHR_REFERER'] || request.referer # TODO: change this when turbolinks is updated
  end

  def update
    if @competition.update_attributes(params[:competition])
      flash[:success] = "Competition updated"
      redirect_to @competition
    else
      render 'edit'
    end
  end

  def show
    add_breadcrumb @competition, competition_path(@competition)
    if request.path != competition_path(@competition)
      redirect_to @competition, status: :moved_permanently
    end
  end

  def index
    @competitions = @competitions.unexpired.uniq
  end

  def destroy
    @competition.destroy
    redirect_to competitions_path
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.haml
= simple_form_for @competition do |f|
  = f.input :title
  = f.input :description, :input_html => { :class => 'span10', :rows => '5' }
  = f.input :deadline, :as => :string, :input_html => { :class => 'datepicker' }
  / = f.input :public, :inline_label => "Display Publicly", :label => false
  = f.button :submit
  = link_to 'Cancel', session.delete(:return_to)

app/views/competitions/create.html.haml
%h1 Competitions#create
%p Find me in app/views/competitions/create.html.haml

app/views/competitions/destroy.html.haml
%h1 Competitions#destroy
%p Find me in app/views/competitions/destroy.html.haml

app/views/competitions/edit.html.haml
%h1 Edit #{@competition}
= render 'form'

app/views/competitions/index.html.haml
.row
  %h1.span8 Available Competitions
  .span4.new-story-button
    = link_to new_competition_path, :class => 'btn btn-primary' do
      %i.icon-pencil.icon-white
      New Competition
%table.table.table-hover.competitions
  %th Competitions
  %th Deadline
  %th Actions
  - @competitions.try(:each) do |c|
    %tr 
      %td= link_to c.title, c
      %td= c.deadline.to_s(:ordinal)
      %td
        = link_to new_competition_submission_path(c), class: 'btn btn-small btn-success',title: "Submit" do
          %i.icon-envelope.icon-white
          Submit
        - if can? :delete, c
          = link_to c, method: :delete, class: 'pull-right', data: { confirm: "Are you sure you want to delete this competition?" }, title: "Delete?" do
            %i.icon-trash
        - if can? :edit, c
          = link_to edit_competition_path(c), class: 'pull-right', title: 'Edit' do
            %i.icon-edit

app/views/competitions/new.html.haml
%h1 Create a New Competition
= render 'form'

app/views/competitions/show.html.haml
.row.header
  %h1.span8.competition-title #{@competition}
  - if can? :edit, @competition
    .span4
      .btn-group.competition-actions-button
        %button.btn.btn-info.dropdown-toggle{"data-toggle" => "dropdown"}
          Competition Options
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to edit_competition_path(@competition) do
              %i.icon-edit
              Edit
          / %li
          /   %a{:href => "#"} 
          /     %i.icon-user
          /     Invite a Judge
          %li
            = link_to new_competition_submission_path(@competition) do
              %i.icon-envelope
              Submit a Story
          - if @competition.public?
            %li.divider
            %li
              %a{:href => '#', :'data-target' => "#share", 'data-toggle' => 'modal'} Share link
  - else
    .span4.new-story-button
      = link_to new_competition_submission_path(@competition), :class => 'btn btn-primary' do
        %i.icon-envelope.icon-white
        Submit a Story
    
  %p.span12.muted
    %small 
      Deadline: 
      %span{class: @competition.expires_today && "label label-important"} #{@competition.deadline.to_s(:ordinal)}

%p.description= display_as_html @competition.description

- if current_user.try(:has_submitted_as_participant?, @competition)
  .alert.alert-success
    You have submitted to this competition.
  %table.table.table-hover
    %th Story
    %th Date Submitted
    - current_user.submissions_for(@competition).includes(:story, :competition).each do |s|
      %tr
        %td= link_to s.story, [s.competition, s]
        %td= s.created_at.to_s(:ordinal)


- if can? :vote, @competition
  %h3= link_to "View All Submissions", competition_submissions_path(@competition)
  %table.table.table-hover.competition_submissions
    %th Author
    %th Story
    %th Vote
    - @competition.submissions.for_consideration.includes(:story, :user, :competition).each do |s|
      %tr{id: "submission_row_#{s.id}"}
        %td= s.user
        %td
          - if can? :read, s
            = link_to s.story, [s.competition, s]
          - else
            = s.story
        %td
          = render 'submissions/voting', klass: 'voting-table', submission: s

#share.modal.hide.fade{tabindex: '-1', role: 'dialog', :'aria-labelledby' => 'Share Link', :'aria-hidden' => 'true'}
  .modal-header
    %button.close{:'data-dismiss' => 'modal', :'aria-hidden' => 'true'} x
    %h3#shareLabel Share this competition
  .modal-body
    .well.well-small= competition_url(@competition)
  .modal-footer
    %button.btn{:'data-dismiss' => 'modal', :'aria-hidden' => true} Close