config/routes.rb
CompositionCompetition::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  authenticated :user do
    root :to => 'home#authenticated_index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do 
    resources :stories
  end
  resources :competitions do
    resources :submissions do
      member {post :vote}
    end
  end
end

app/views/shared/_new_user.html.haml
= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f|
  = f.error_notification
  = f.input :name, :autofocus => true
  = f.input :email, :required => true
  = f.input :password, :required => true
  = f.button :submit, 'Sign up', :class => 'btn-primary'

app/views/shared/_signin.html.haml
= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-vertical' }) do |f|
  = f.input :email, :placeholder => 'email', :autofocus => true, :label => false
  = f.input :password, :inline_label => '', :placeholder => 'password', :label => false
  = f.input :remember_me, :inline_label => 'Yes, remember me', :label_html => { :class => 'remember-me-label' }, :input_html => { :checked => true }, :label => false, :as => :boolean if devise_mapping.rememberable?
  = f.button :submit, "Sign in", :class => 'btn-primary'
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name), :class => 'forgot-password'

/ %form{"accept-charset" => "UTF-8", :action => "login", :method => "post"}
/         %input#username{:name => "username", :placeholder => "Username", :style => "margin-bottom: 15px;", :type => "text"}
/           %input#password{:name => "password", :placeholder => "Password", :style => "margin-bottom: 15px;", :type => "password"}
/             %input#remember-me{:name => "remember-me", :style => "float: left; margin-right: 10px;", :type => "checkbox", :value => "1"}
/               %label.string.optional{:for => "user_remember_me"} Remember me
/               %input#sign-in.btn.btn-primary.btn-block{:type => "submit", :value => "Sign In"}
/                 %label{:style => "text-align:center;margin-top:5px"} or
/                 %input#sign-in-google.btn.btn-primary.btn-block{:type => "button", :value => "Sign In with Google"}
/                   %input#sign-in-twitter.btn.btn-primary.btn-block{:type => "button", :value => "Sign In with Twitter"}

app/views/shared/_tracking.html.haml
:javascript
  var GoSquared = {};
  GoSquared.acct = "GSN-649611-J";
  (function(w){
    function gs(){
      w._gstc_lt = +new Date;
      var d = document, g = d.createElement("script");
      g.type = "text/javascript";
      g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
      var s = d.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(g, s);
    }
    w.addEventListener ?
      w.addEventListener("load", gs, false) :
      w.attachEvent("onload", gs);
  })(window);