config/routes.rb
CompositionCompetition::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  authenticated :user do
    root :to => 'home#authenticated_index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do 
    resources :stories
  end
  resources :competitions do
    resources :submissions do
      member {post :vote}
    end
  end
end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#  slug       :string(255)
#  public     :boolean
#

class Story < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :user_id, :text, :title, :competition, :submissions, :public
  friendly_id :title, use: :slugged

  has_paper_trail

  belongs_to :user
  has_many :submissions, :dependent => :destroy
  has_many :competitions, :through => :submissions

  validates :user, :presence => true
  validates :title, :presence => true
  validates :text, :presence => true

  def to_s
    self.title.titleize
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  (skip_before_filter :authenticate_user!, :only => [:show]) if lambda { 
    if params[:id]
      @story = Story.find(params[:user_id], params[:id])
      @story and @story.public?
    else
      false
    end
  }

  add_breadcrumb "Stories", :user_stories_path, only: %w{index show new edit create}

  def new
    @story = Story.new
    @user = current_user
    session[:return_to] ||= request.env['HTTP_X_XHR_REFERER'] || request.referer # TODO: change this when turbolinks is updated
    session[:unclobbered_return_to] = request.env['HTTP_X_XHR_REFERER']
  end

  def create
    @story = current_user.stories.build(params[:story])
    if @story.save
      flash[:success] = "Story created"
      # redirect_to [current_user, @story]
      redirect_to session.delete(:unclobbered_return_to)
    else
      @user = current_user
      render 'new'
    end
  end

  def show
    if user_signed_in?
      add_breadcrumb @story, user_story_path(current_user,@story)
    end
    if request.path != user_story_path(@story.user, @story)
      redirect_to user_story_path(@story.user, @story), status: :moved_permanently
    end
  end

  def index
    @my_stories = @stories.unscoped.where(user_id: current_user)
  end

  def edit
    add_breadcrumb @story, user_story_path(@story.user, @story)
    add_breadcrumb "Edit", edit_user_story_path(@story.user, @story)
    session[:return_to] ||= request.env['HTTP_X_XHR_REFERER'] || request.referer # TODO: change this when turbolinks is updated
  end

  def update
    if @story.save
      flash[:success] = "Story updated"
      redirect_to user_story_path(@story.user, @story)
    else
      render 'edit'
    end
  end

  def destroy
    @story.destroy
    redirect_to user_stories_path(current_user)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= simple_form_for [user, story] do |f|
  = f.input :title, autofocus: true, placeholder: "Title", label: false
  = f.input :text, :input_html => { :class => 'span10' }, placeholder: "Write or paste your story here...", label: false
  = f.input :public, label: false, inline_label: "Publicly viewable?"
  = f.button :submit, :disable_with => 'Submiting...'
  = link_to 'Cancel', session.delete(:return_to)

app/views/stories/_story.html.haml
.story-page.span10
  .story.span8
    %h1= story.title
    %p by #{story.user}
    %p= display_as_html(story.text)

app/views/stories/create.html.haml
%h1 Stories#create
%p Find me in app/views/stories/create.html.haml

app/views/stories/destroy.html.haml
%h1 Stories#destroy
%p Find me in app/views/stories/destroy.html.haml

app/views/stories/edit.html.haml
= render 'form', user: @story.user, story: @story

app/views/stories/index.html.haml
- unless current_user.admin?
  .row
    %h1.span8 #{current_user}'s Stories
    .span4.new-story-button
      = link_to new_user_story_path, :class => 'btn btn-primary' do
        %i.icon-pencil.icon-white
        New Story
  %table.table.table-hover
    %th Title
    %th Date Created
    - @my_stories.includes(:user).each do |s|
      %tr 
        %td= link_to s.title, [s.user, s]
        %td.small.muted= s.created_at.to_s(:ordinal)
- else
  .row
    %h1.span8 All Stories
    .span4.new-story-button
      = link_to new_user_story_path, :class => 'btn btn-primary' do
        %i.icon-pencil.icon-white
        New Story
  %table.table.table-hover
    %th Title
    %th Date Created
    %th User
    - @stories.includes(:user).each do |s|
      %tr 
        %td= link_to s.title, [s.user, s]
        %td.small.muted= s.created_at.to_s(:ordinal)
        %td= link_to s.user, s.user

app/views/stories/new.html.haml
%h1 New Story
= render 'form', user: @user, story: @story

app/views/stories/show.html.haml
- if can? :delete, @story
  .row
    .offset8.span4
      .btn-group.story-actions-button
        %button.btn-info.btn.dropdown-toggle{"data-toggle" => "dropdown"}
          Story Options
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to edit_user_story_path(@story.user, @story) do
              %i.icon-edit
              Edit
          %li
            = link_to "#delete", role: "button", data: {toggle: "modal"} do
              %i.icon-trash
              Delete
          - if @story.public?
            %li.divider
            %li
              %a{:href => '#', :'data-target' => "#share", 'data-toggle' => 'modal'} Share link
    #delete.modal.small.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "DeleteModal", :role => "dialog", :tabindex => "-1"}
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h3#myModalLabel Delete Confirmation
      .modal-body
        %p.error-text Are you sure you want to delete this story?
      .modal-footer
        %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Cancel
        = link_to user_story_path(@story.user, @story), method: :delete do
          %button.btn.btn-danger{"data-dismiss" => "modal"} Delete
= render @story

#share.modal.hide.fade{tabindex: '-1', role: 'dialog', :'aria-labelledby' => 'Share Link', :'aria-hidden' => 'true'}
  .modal-header
    %button.close{:'data-dismiss' => 'modal', :'aria-hidden' => 'true'} x
    %h3#shareLabel Share this competition
  .modal-body
    .well.well-small= user_story_url(@story)
  .modal-footer
    %button.btn{:'data-dismiss' => 'modal', :'aria-hidden' => true} Close