config/routes.rb
CompositionCompetition::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  authenticated :user do
    root :to => 'home#authenticated_index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do 
    resources :stories
  end
  resources :competitions do
    resources :submissions do
      member {post :vote}
    end
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%a{class: "btn btn-navbar", data: {toggle: "collapse", target: ".nav-collapse"}}
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar
= link_to "Composition Competition", root_path, :class => 'brand'
%div.nav-collapse.collapse 
  %ul.nav.pull-right
    - if user_signed_in?
      = nav_link 'Stories', user_stories_path(current_user)
      = nav_link 'Competitions', competitions_path
      %li.dropdown
        %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
          Welcome, #{current_user.name}
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to edit_user_registration_path do
              %i.icon-user
              Edit Account
          - if current_user.admin?
            %li
              = link_to rails_admin_path, :'data-no-turbolink' => true do
                %i.icon-exclamation-sign
                Admin
          %li.divider
          %li
            = link_to destroy_user_session_path, :method=>'delete' do
              %i.icon-off
              Logout
    - else
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          Sign In
          %strong.caret
        .dropdown-menu{:style => "padding: 15px; padding-bottom: 0px;"}
          = render 'shared/signin'
      %li
        = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Composition Competition"
      %meta{:content => content_for?(:description) ? yield(:description) : "Composition Competition", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Serif"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
    :javascript
      (function (d, t) {
        var bh = d.createElement(t), s = d.getElementsByTagName(t)[0]
        bh.type = 'text/javascript'
        bh.src = '//www.bugherd.com/sidebarv2.js?apikey=pjcxrfkzds6cnxqwtixafq'
        s.parentNode.insertBefore(bh, s)
        })(document, 'script')
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
    .container
      .row
        .span12
          - if user_signed_in?
            = render_breadcrumbs :builder => ::BootstrapBreadcrumbsBuilder
          = render 'layouts/messages'
          = yield
      %footer
      / ! end of .container
    / ! end of #main
  = render 'shared/tracking'